name: Angular CRUD CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test
        npm run coverage
      working-directory: ./angular-crud
    - name: package angular-crud
      run: npm pack
      working-directory: ./angular-crud
    - name: generate CRUD and run tests
      run: |
        npm i -g @angular/cli
        npm i
        npm i --no-save ../angular-crud/*.tgz
        mkdir -p src/app/hotel
        mv model.json src/app/hotel/.
        ng g angular-crud:crud-module hotel
        ng test --no-watch --no-progress --browsers=ChromeHeadlessCI
      working-directory: ./demo
      env:
        CI: true
